---
name: container-gpu-test

releases:
  - name: gpu-test
    version: latest

stemcells:
  - alias: default
    os: ubuntu-noble
    version: "1.562-nvidia"

instance_groups:
  - name: container-gpu-validation
    instances: 1
    azs: [z1]
    vm_type: gpu-small
    stemcell: default
    networks:
      - name: private
    lifecycle: errand
    jobs:
      - name: container-gpu-errand-noble
        release: gpu-test

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-1200000
  update_watch_time: 30000-1200000

variables: []
